name: 'Action ESLint'
description: 'GitHub Action that runs ESLint on files changed in a Pull Request'
author: 'sibiraj-s'

branding:
  icon: 'check-square'
  color: 'green'

runs:
  using: 'node12'
  main: 'dist/index.js'

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    required: false
    default: ${{ github.token }}
  eslint-args:
    description: 'ESLint CLI flags'
    required: false
    default: ''
  extensions:
    description: 'Extensions to filter'
    required: false
    default: 'js'
  annotations:
    description: 'Enable or disable annotations'
    required: false
    default: true
  path-link:
    description: 'Creates a link from path of process.cwd() to node_modules if necessary'
    required: false
    default: ''
