name: Lint

env:
  NODE_VERSION: 24

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          # @fixme: https://github.com/nektos/act/issues/989
          cache: ${{ !env.ACT && 'npm' || '' }}

      - run: npm ci
      - run: npm ls --depth=0
      - run: npm test

      - uses: ./
        with:
          extensions: 'js,ts'
          ignore-patterns: dist/
